### ISSUE TITLE
Responsive Margin

### ISSUE THREAD

**Issue by CHEWX** [bigbite/macy.js#41]
Hi,

Usually when using Macy I'm using it in a responsive grid environment. 

As such it would be good if you could parse percentage margins.

```
{
    x: '4%',
    y: 40 
}
```

Like the above for example.

Thanks.

**Comment by jrmd** [comment]
Hey @CHEWX ,

I have implemented the first version of this, currently custom units are only supported on the x property, due to how the height of the container is calculated. 

In the future i'll work on reworking the how the height is calculated to add support for custom Y values

**Comment by ghost** [comment]
Any news on this?

**Comment by jrmd** [comment]
> Any news on this?

Hey @dnnsjsk 

As per my comment above; this was implemented for the x margin around a year ago :)
