### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Souldrinker** [bigbite/macy.js#49]
I needed a masonry library and wanted to avoid jQuery and other dependencies and so far this library seem to be really easy to set up and get to work as I wanted :-)

But, I'm curious about one thing. On the web page it says "Macy.js is a lightweight, dependency-free, 4kb masonry layout library", so how come you still have dependencies (not devDependencies) to babel-eslint and rollup-plugin-eslint?

I was expecting to get 1 package when doing a "npm install macy", but got 89...

**Comment by jrmd** [comment]
Hey @Souldrinker 

Thanks for pointing this out, these should be in devDependencies and I will roll out a fix later today. These must have been added to dependencies in error. 

Sorry for the inconvenience.

**Comment by Souldrinker** [comment]
Not meaning to stress you, but I thought I could mention that I ran into an issue due to these dependencies. I removed the package-lock.json and the node_modules folder and tried to re-run npm install, but after that I ran into this issue with webpack which at first might look unrelated:
https://discourse.aurelia.io/t/aurelia-dialog-2-0-0-rc-5-error/2160

But after following the link to the webpack issue (https://github.com/webpack/webpack/issues/8656) I it seems like there seems to be an issue with the combination of acorn/npm/webpack and since the rollup-plugin-eslint that you accidently seem to have gotten as a dependency rather then a devDependency references an older version of acorn stuff seem to break:
npm ls acorn
+-- macy@2.3.2
| `-- rollup-plugin-eslint@3.0.0
|   `-- eslint@3.19.0
|     `-- espree@3.5.4
|       +-- acorn@5.7.3
|       `-- acorn-jsx@3.0.1
|         `-- acorn@3.3.0
`-- webpack@4.29.5
  `-- UNMET PEER DEPENDENCY acorn@6.1.0

npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-dynamic-import@4.0.0

I tried some of the workarounds specified here: https://github.com/webpack/webpack/issues/8656#issuecomment-456713191
...and also tried to again delete the lock file/node_modules folder without luck, so what I finally did to get my project running again was to uninstall macy and comment out the javascript using macy. Then again remove package-lock.json/node_modules and do a npm install and finally after that reinstall macy and uncomment the code again.

I'll probably be careful about touching the lock file for now, but anyway it would be very nice if you could change these dependencies to avoid issues in the future.

**Comment by jrmd** [comment]
Hey @Souldrinker I have moved all dependencies into devDependencies, hopefully this will solve the above issues.

Sorry for the incovenience
