### ISSUE TITLE
breaktAt based on container width instead of viewport width?

### ISSUE THREAD

**Issue by KjeldSchmidt** [bigbite/macy.js#50]
Hey, thanks for all the great work.

I'm currently setting up breakpoints for a new layout and it took me a while to realize that the breakpoints are based on the total viewport width instead of the container width (even though the readme states that fact quite clearly...). This seems counterintuitive to me. In my case, the container is simply 80% of the viewport, so calculations aren't a big problem, but I wondered if it would be possible to add an option for this?

I'll gladly try implementing this option myself if I get a go-ahead and maybe a hint as to where the code might need to be adapted.

Thanks,
Kjeld

**Comment by jrmd** [comment]
Hey @KjeldSchmidt 

I have implemented this as an option in the latest release of macy, you can now do this by adding this `useContainerForBreakpoints: true` to your macy options. 

Let me know if you have any issues with this and I will aim to resolve them

Thanks,
Jerome
