### ISSUE TITLE
Promise IE11 fallback

### ISSUE THREAD

**Issue by CHEWX** [bigbite/macy.js#53]
Hi,

Instead of the script just erroring and killing the page, could we have a graceful fallback to just a single column, or basically, just don't init Macy.

I don't really want to use a polyfill, so would rather Macy didn't run at all and IE11 just get's CSS.

Thanks,
Tom

**Comment by jrmd** [comment]
Hi @CHEWX 

Thanks for reporting this, i have added an option to prevent macy running if promises arent supported, `cancelLegacy`, As users can still use macy on IE11 without images.

Let me know if you come across any issues with this implementation.

Regards,
Jerome
